def maxStr(l):
    max=0 #O(1)
    for i in l: #O(len(l))
        count=0 O(1)
        for j in i: #O(len(i))
            count+=1 #O(1)
        if count > max: #O(1)
            max=count #O(1)
    return max #O(1)
print(maxStr(["asasf","af","dsa","dddasdas"]))
#O(len(l)*len(i))